# Generated by Django 4.1.10 on 2023-08-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconblock',
            name='img',
            field=models.FileField(upload_to='main_icons/', verbose_name='icon'),
        ),
    ]
