# Generated by Django 4.1.3 on 2022-12-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_cats', '0001_initial'),
        ('logistics', '0002_remove_order_extra_cargo_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.ManyToManyField(blank=True, to='log_cats.deliverytype', verbose_name='Type of delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='log_cats.extraservice', verbose_name='Extra services'),
        ),
        migrations.DeleteModel(
            name='DeliveryType',
        ),
        migrations.DeleteModel(
            name='ExtraService',
        ),
    ]
