# Generated by Django 4.1.3 on 2022-12-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_delete_deliverytype_delete_extraservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date_wanted',
            field=models.DateField(blank=True, null=True, verbose_name='Wanted date of delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date_wanted',
            field=models.DateField(default=datetime.datetime(2022, 12, 20, 13, 19, 8, 731088, tzinfo=datetime.timezone.utc), verbose_name='Wanted date of pickup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_spaces',
            field=models.IntegerField(default=0, verbose_name='Cargo spaces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_value',
            field=models.FloatField(default=0, verbose_name='Cargo value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_volume',
            field=models.FloatField(default=0, verbose_name='Cargo volume, m3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_weight',
            field=models.FloatField(default=0, verbose_name='Cargo weight, kg'),
            preserve_default=False,
        ),
    ]
