# Generated by Django 4.1.3 on 2023-01-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_orderstatus_options_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payer_passport',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payer_type',
        ),
    ]
