# Generated by Django 4.1.3 on 2023-01-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_order_payer_passport_remove_order_payer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payer_tin',
            field=models.CharField(default=0, max_length=15, verbose_name='Payer TIN'),
            preserve_default=False,
        ),
    ]
