# Generated by Django 4.1.3 on 2023-01-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_order_delivery_type_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show_cargo_price_in_receipt',
            field=models.BooleanField(default=True, verbose_name='Show cargo price in receipt'),
        ),
    ]
