# Generated by Django 4.1.3 on 2023-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_contractorbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorbill',
            name='taxes',
            field=models.IntegerField(blank=True, choices=[(None, 'No taxes'), (20, '20%')], default=20, null=True, verbose_name='Taxes'),
        ),
    ]
