# Generated by Django 4.1.9 on 2023-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_contractorbill_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receiver',
            field=models.CharField(choices=[('llc', 'Cargo Logika LLC'), ('ie', 'IE Nikulin Eugene')], default='llc', max_length=5, verbose_name='Payment receiver'),
        ),
    ]
