# Generated by Django 4.1.3 on 2023-01-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_remove_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contract number'),
        ),
    ]
